services:
    _defaults:
        autowire: true
        autoconfigure: true

    SymfonyEs\Bundle\PersistenceBundle\Service\:
        resource: '../../Service/*'

    SymfonyEs\Bundle\PersistenceBundle\Service\PersistenceBundleTest:
        public: true

    SymfonyEs\Bundle\PersistenceBundle\EventListener\DoctrineSubscriber:
        autowire: true
        autoconfigure: true

